<?php

use Instagram2Vk\Classes\VkPostTransformer;


class VkPostTransformerTest extends PHPUnit_Framework_TestCase
{
    private $sample_post = "";

    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $json_post = file_get_contents(__DIR__."/static/post.json");
        $this->sample_post = json_decode($json_post, true);



    }


    function test_vk_formatter_with_image()
    {

        $posts = [$this->sample_post];

        $vkFormatter = new VkPostTransformer();
        $vkFormatter->setPost($posts[0]);

        $this->assertEquals($vkFormatter->getText(), $posts[0]["caption"]['text']);
        $this->assertEquals($vkFormatter->getImageUrl(), $posts[0]["images"]["standard_resolution"]["url"]);

    }


}
